# Generated by Django 5.0.1 on 2024-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_appointment_appointmenttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttable',
            name='idRandomly',
            field=models.CharField(max_length=255),
        ),
    ]
